import 'dart:io';

import 'package:test/test.dart';
import 'package:path/path.dart' as p;
import 'package:waddlectl/run_app.dart';

/// Drives most `runWaddlectl` code paths for coverage (temp SQLite each time).
void main() {
  late String dbPath;

  setUp(() {
    final tmp = Directory.systemTemp.createTempSync('waddlectl_cov');
    dbPath = p.join(tmp.path, 'waddle_view.sqlite');
    File(dbPath).writeAsStringSync('');
  });

  tearDown(() {
    final f = File(dbPath);
    final dir = f.parent;
    try {
      if (f.existsSync()) {
        f.deleteSync();
      }
      if (dir.existsSync()) {
        dir.deleteSync(recursive: true);
      }
    } on Object {
      // ignore
    }
  });

  List<String> w(List<String> tail) => ['--database', dbPath, ...tail];

  test('screens tickers providers curator config surface', () async {
    expect(await runWaddlectl(w(['screens', 'list'])), 0);
    expect(await runWaddlectl(w(['screens', 'describe', 'missing'])), 0);
    expect(await runWaddlectl(w(['tickers', 'list'])), 0);
    expect(await runWaddlectl(w(['tickers', 'describe', 'missing'])), 0);
    expect(await runWaddlectl(w(['providers', 'list'])), 0);
    expect(await runWaddlectl(w(['providers', 'describe', 'missing'])), 0);
    expect(await runWaddlectl(w(['curator', 'describe-program'])), 0);
    expect(
      await runWaddlectl(
        w(['curator', 'update-program', '--program-duration-seconds=120']),
      ),
      0,
    );
    expect(await runWaddlectl(w(['curator', 'limits', 'list'])), 0);
    expect(
      await runWaddlectl(w(['curator', 'limits', 'describe', 'missing'])),
      0,
    );
    expect(
      await runWaddlectl(
        w([
          'curator',
          'limits',
          'update',
          'news',
          '--min-placements-per-program=0',
        ]),
      ),
      0,
    );
    expect(await runWaddlectl(w(['config', 'list'])), 0);
  });

  test('invalid usage returns 64', () async {
    expect(await runWaddlectl(w(['config', 'get'])), 64);
  });

  test('unknown command returns 64', () async {
    expect(await runWaddlectl(w(['secrets', 'list'])), 64);
  });

  test('backup create schedule restore without secrets', () async {
    expect(await runWaddlectl(w(['config', 'list'])), 0);
    final tmp = Directory.systemTemp.createTempSync('waddle_cli_bu');
    addTearDown(() => tmp.deleteSync(recursive: true));
    final outDir = p.join(tmp.path, 'out');
    Directory(outDir).createSync();
    expect(
      await runWaddlectl(
        w(['backup', 'create', '--format=zip', '--output=$outDir']),
      ),
      0,
    );
    final zips = Directory(outDir)
        .listSync()
        .whereType<File>()
        .where((f) => f.path.toLowerCase().endsWith('.zip'))
        .toList();
    expect(zips.length, 1);
    expect(await runWaddlectl(w(['backup', 'schedule'])), 0);
    await File(dbPath).writeAsBytes([0, 1, 2, 3], flush: true);
    expect(
      await runWaddlectl(
        w(['backup', 'restore', '--file=${zips.first.path}', '--yes']),
      ),
      0,
    );
    expect(await runWaddlectl(w(['config', 'list'])), 0);
  });

  test('backup restore usage without file returns 64', () async {
    expect(await runWaddlectl(w(['backup', 'restore'])), 64);
  });

  test('sqlite export-seed', () async {
    expect(await runWaddlectl(w(['config', 'list'])), 0);
    final tmp = Directory.systemTemp.createTempSync('wctl_seed_out');
    addTearDown(() => tmp.deleteSync(recursive: true));
    final out = p.join(tmp.path, 'seed.sql');
    expect(await runWaddlectl(w(['sqlite', 'export-seed', '--file=$out'])), 0);
    final body = File(out).readAsStringSync();
    expect(body, contains('PRAGMA foreign_keys=OFF'));
    expect(body, contains('-- Generated by waddlectl sqlite export-seed'));
  });
}
