#!/usr/bin/env python3
"""Export the local dev ``waddle_view.sqlite`` snapshot to a single SQL seed file.

Resolves the database path the same way as ``deploy/dev-pi/install_main_to_pi.py``
(Flutter ``path_provider`` application support layout).

The output is **data only** (no DDL): ``DELETE`` statements clear existing rows (with foreign
keys disabled), ``sqlite_sequence`` is reset when present, then ``INSERT`` statements replay
the exported rows. Apply only against a database that **already matches** the app
schema version (for example after the Flutter app created or migrated the file).

Examples::

    python tool/export_waddle_sqlite_seed_sql.py -o deploy/dev-pi/my_seed.sql
    python tool/export_waddle_sqlite_seed_sql.py --db \"C:\\\\Users\\\\me\\\\AppData\\\\Roaming\\\\com.waddleview\\\\waddle_display\\\\waddle_view.sqlite\" -o seed.sql
    python tool/export_waddle_sqlite_seed_sql.py --stdout

Do **not** commit files that contain secrets (OAuth tokens in tables, API keys in
``provider_settings``, etc.). Prefer redacting or using a throwaway dev database.
"""
from __future__ import annotations

import argparse
import importlib.util
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent


def _load_install_main_to_pi():
    path = REPO_ROOT / "deploy" / "dev-pi" / "install_main_to_pi.py"
    spec = importlib.util.spec_from_file_location("install_main_to_pi", path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (bytes, bytearray, memoryview)):
        b = bytes(value)
        return "X'" + b.hex() + "'"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            raise ValueError(f"Unsupported float in SQL export: {value!r}")
        return repr(value)
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    raise TypeError(f"Unsupported column type {type(value)!r} for SQL export")


def _list_user_tables(conn: sqlite3.Connection) -> list[str]:
    cur = conn.execute(
        """
        SELECT name FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    )
    return [row[0] for row in cur.fetchall()]


def _table_columns(conn: sqlite3.Connection, table: str) -> list[tuple[int, str, str]]:
    """Return (cid, name, declared type) for each column in stable pragma order."""
    cur = conn.execute(f"PRAGMA table_info({_quote_ident(table)})")
    rows: list[tuple[int, str, str]] = []
    for cid, name, ctype, notnull, dflt_value, pk in cur.fetchall():
        rows.append((cid, name, ctype or ""))
    rows.sort(key=lambda r: r[0])
    return rows


def _emit_table_inserts(
    conn: sqlite3.Connection,
    table: str,
    col_names: list[str],
    out_lines: list[str],
) -> int:
    if not col_names:
        return 0
    qcols = ", ".join(_quote_ident(c) for c in col_names)
    quoted_table = _quote_ident(table)
    cur = conn.execute(f"SELECT {qcols} FROM {quoted_table}")
    count = 0
    for row in cur:
        values_sql = ", ".join(_sql_literal(v) for v in row)
        out_lines.append(f"INSERT INTO {quoted_table} ({qcols}) VALUES ({values_sql});")
        count += 1
    return count


def export_seed_sql(
    db_path: Path,
    *,
    include_sqlite_sequence_rows: bool = False,
) -> str:
    """Return a full SQL script string."""
    uri = f"file:{db_path.resolve().as_posix()}?mode=ro"
    conn = sqlite3.connect(uri, uri=True)
    try:
        tables = _list_user_tables(conn)
        lines: list[str] = []
        utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        lines.append(f"-- Generated by tool/export_waddle_sqlite_seed_sql.py at {utc}")
        lines.append(f"-- Source database: {db_path.resolve()}")
        lines.append("-- Data-only seed: requires matching Drift schema on the target file.")
        lines.append("PRAGMA foreign_keys=OFF;")
        lines.append("BEGIN IMMEDIATE;")

        # Clear data (FK order irrelevant while disabled).
        if "sqlite_sequence" in [
            r[0]
            for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='sqlite_sequence'"
            ).fetchall()
        ]:
            lines.append("DELETE FROM sqlite_sequence;")

        for t in reversed(tables):
            lines.append(f"DELETE FROM {_quote_ident(t)};")

        total_inserts = 0
        for t in tables:
            cols = _table_columns(conn, t)
            col_names = [c[1] for c in cols]
            n = _emit_table_inserts(conn, t, col_names, lines)
            total_inserts += n

        if include_sqlite_sequence_rows:
            seq_cols = _table_columns(conn, "sqlite_sequence")
            seq_names = [c[1] for c in seq_cols]
            if seq_names:
                _emit_table_inserts(conn, "sqlite_sequence", seq_names, lines)

        lines.append("COMMIT;")
        lines.append("PRAGMA foreign_keys=ON;")
        lines.append(f"-- Rows exported (INSERT statements): {total_inserts}")
    finally:
        conn.close()

    return "\n".join(lines) + "\n"


def main(argv: Iterable[str] | None = None) -> int:
    im = _load_install_main_to_pi()
    parser = argparse.ArgumentParser(
        description="Dump waddle_view.sqlite data to a single SQL seed script.",
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=None,
        help="Path to waddle_view.sqlite (default: same search as install_main_to_pi.py).",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Write SQL to this file (default when neither -o nor --stdout: seed next to DB).",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Write SQL to stdout instead of a file.",
    )
    parser.add_argument(
        "--include-sqlite-sequence-rows",
        action="store_true",
        help="Also emit INSERTs for sqlite_sequence after data (normally not needed).",
    )
    ns = parser.parse_args(list(argv) if argv is not None else None)

    db_path = im.resolve_local_sqlite_path(ns.db)
    sql = export_seed_sql(
        db_path,
        include_sqlite_sequence_rows=ns.include_sqlite_sequence_rows,
    )

    if ns.stdout:
        # Avoid Windows console code page mangling non-ASCII cell values.
        sys.stdout.buffer.write(sql.encode("utf-8"))
        return 0

    out_path = ns.output
    if out_path is None:
        out_path = db_path.with_name(db_path.stem + "_seed.sql")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(sql, encoding="utf-8", newline="\n")
    print(f"Wrote {out_path} ({len(sql)} bytes) from {db_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
