import 'package:flutter/material.dart';

/// Maps [ContentCategories.materialIconName] from the database to [IconData].
///
/// Unknown names fall back to [Icons.label_outline] so new DB values do not crash UI.
IconData contentCategoryMaterialIcon(String? materialIconName) {
  switch (materialIconName) {
    case 'article':
      return Icons.article_outlined;
    case 'public':
      return Icons.public;
    case 'flag':
      return Icons.flag;
    case 'memory':
      return Icons.memory;
    case 'attach_money':
      return Icons.attach_money;
    case 'science':
      return Icons.science_outlined;
    case 'photo_library':
      return Icons.photo_library_outlined;
    case 'wallpaper':
      return Icons.wallpaper_outlined;
    case 'nights_stay':
      return Icons.nights_stay_outlined;
    case 'rocket_launch':
      return Icons.rocket_launch_outlined;
    case 'photo_camera':
      return Icons.photo_camera_outlined;
    case 'forest':
      return Icons.forest_outlined;
    case 'local_florist':
      return Icons.local_florist_outlined;
    case 'landscape':
      return Icons.landscape_outlined;
    case 'beach_access':
      return Icons.beach_access;
    case 'terrain':
      return Icons.terrain;
    case 'sentiment_satisfied':
      return Icons.sentiment_satisfied_alt_outlined;
    case 'favorite':
      return Icons.favorite_border;
    case 'pets':
      return Icons.pets;
    case 'school':
      return Icons.school_outlined;
    case 'work':
      return Icons.work_outline;
    case 'card_giftcard':
      return Icons.card_giftcard;
    case 'egg_alt':
      return Icons.egg_outlined;
    case 'dark_mode':
      return Icons.dark_mode_outlined;
    case 'restaurant':
      return Icons.restaurant;
    case 'calculate':
      return Icons.calculate_outlined;
    case 'map':
      return Icons.map_outlined;
    case 'stars':
      return Icons.stars_outlined;
    case 'movie':
      return Icons.movie_outlined;
    case 'person':
      return Icons.person_outline;
    case 'sports_soccer':
      return Icons.sports_soccer;
    case 'menu_book':
      return Icons.menu_book_outlined;
    case 'self_improvement':
      return Icons.self_improvement;
    case 'water':
      return Icons.water_drop_outlined;
    case 'family_restroom':
      return Icons.family_restroom;
    case 'account_circle':
      return Icons.account_circle_outlined;
    case 'business_center':
      return Icons.business_center_outlined;
    case 'church':
      return Icons.church_outlined;
    case 'volunteer_activism':
      return Icons.volunteer_activism_outlined;
    case 'shopping_cart':
      return Icons.shopping_cart_outlined;
    case 'local_hospital':
      return Icons.local_hospital_outlined;
    case 'manage_search':
      return Icons.manage_search_outlined;
    case 'lunch_dining':
      return Icons.lunch_dining_outlined;
    case 'restaurant_menu':
      return Icons.restaurant_menu_outlined;
    case 'coffee':
      return Icons.coffee_outlined;
    case 'code':
      return Icons.code_outlined;
    case 'devices':
      return Icons.devices_outlined;
    case 'home':
      return Icons.home_outlined;
    case 'apartment':
      return Icons.apartment_outlined;
    case 'music_note':
      return Icons.music_note_outlined;
    case 'tv':
      return Icons.tv_outlined;
    case 'podcasts':
      return Icons.podcasts_outlined;
    case 'sports_esports':
      return Icons.sports_esports_outlined;
    case 'auto_stories':
      return Icons.auto_stories_outlined;
    case 'fitness_center':
      return Icons.fitness_center_outlined;
    case 'child_care':
      return Icons.child_care_outlined;
    case 'directions_car':
      return Icons.directions_car_outlined;
    case 'yard':
      return Icons.yard_outlined;
    case 'checkroom':
      return Icons.checkroom_outlined;
    case 'palette':
      return Icons.palette_outlined;
    case 'groups':
      return Icons.groups_outlined;
    case 'gavel':
      return Icons.gavel_outlined;
    case 'event':
      return Icons.event_outlined;
    default:
      return Icons.label_outline;
  }
}
