// Generates lib/api/generated/display_about_data.dart and
// assets/generated/third_party_licenses.txt for GET /v1/about.
//
// Run from repo root: dart run apps/waddle_display/tool/generate_about_manifest.dart
// Requires Flutter on PATH for `flutter pub licenses`.
import 'dart:convert';
import 'dart:io';

void main(List<String> args) async {
  final script = Platform.script.toFilePath();
  final displayRoot = Directory(script).parent.parent.path;
  final repoRoot = Directory(displayRoot).parent.parent.path;

  final pubspecPath = '$displayRoot/pubspec.yaml';
  final pubspecText = File(pubspecPath).readAsStringSync();
  final versionMatch = RegExp(r'^version:\s*([^\s+]+)(?:\+(\d+))?', multiLine: true)
      .firstMatch(pubspecText);
  if (versionMatch == null) {
    stderr.writeln('Could not parse version from pubspec.yaml');
    exit(1);
  }
  final appVersion = versionMatch.group(1)!;
  final buildNumber = versionMatch.group(2) ?? '1';

  final licenseUrlMatch =
      RegExp(r'^license_url:\s*(\S+)', multiLine: true).firstMatch(pubspecText);
  final licenseUrl = licenseUrlMatch?.group(1) ??
      'https://github.com/dukk/waddle-view/blob/main/LICENSE';

  final licenseFile = File('$repoRoot/LICENSE');
  final licenseSummary = licenseFile.existsSync()
      ? licenseFile
          .readAsStringSync()
          .split(RegExp(r'\n(?=\d+\. )'))
          .first
          .trim()
      : 'Open Non-Commercial License (ONC) v1.0';

  final lockPath = '$repoRoot/pubspec.lock';
  final lockVersions = _parseLockVersions(File(lockPath).readAsStringSync());

  final deps = <Map<String, String>>[];
  for (final entry in _parsePubspecDependencies(pubspecText, displayRoot)) {
    final name = entry.name;
    if (name == 'flutter') {
      deps.add({
        'name': 'flutter',
        'version': 'sdk',
        'license': 'BSD-3-Clause',
      });
      continue;
    }
    if (entry.path != null) {
      final pkgPubspec = File('${entry.path}/pubspec.yaml');
      if (pkgPubspec.existsSync()) {
        final pkgText = pkgPubspec.readAsStringSync();
        final v = RegExp(r'^version:\s*(\S+)', multiLine: true).firstMatch(pkgText);
        deps.add({
          'name': name,
          'version': v?.group(1) ?? '',
          'license': 'ONC',
        });
      }
      continue;
    }
    deps.add({
      'name': name,
      'version': lockVersions[name] ?? '',
      'license': '',
    });
  }
  deps.sort((a, b) => a['name']!.compareTo(b['name']!));

  final assetsDir = Directory('$displayRoot/assets/generated');
  assetsDir.createSync(recursive: true);
  final licensesPath = '${assetsDir.path}/third_party_licenses.txt';

  var licensesText = '';
  try {
    ProcessResult? result;
    for (final cmd in [
      ['flutter', 'pub', 'licenses'],
      ['dart', 'pub', 'licenses'],
    ]) {
      result = await Process.run(
        cmd[0],
        cmd.sublist(1),
        workingDirectory: displayRoot,
        runInShell: true,
      );
      if (result.exitCode == 0) break;
    }
    if (result != null && result.exitCode == 0) {
      licensesText = (result.stdout as String).trim();
    } else {
      stderr.writeln(
        'pub licenses failed: ${result?.stderr ?? "no flutter/dart pub licenses command"}',
      );
      licensesText =
          'Third-party license text was not generated. Run tool/generate_about_manifest.dart on a machine with Flutter SDK.';
    }
  } catch (e) {
    stderr.writeln('flutter pub licenses skipped: $e');
    licensesText = '(Flutter not available; regenerate licenses when building releases.)';
  }
  File(licensesPath).writeAsStringSync('$licensesText\n');

  final generatedDir = Directory('$displayRoot/lib/api/generated');
  generatedDir.createSync(recursive: true);
  final dartOut = File('${generatedDir.path}/display_about_data.dart');
  final depsJson = jsonEncode(deps);
  final escapedSummary = _dartString(licenseSummary);
  final escapedUrl = _dartString(licenseUrl);
  final escapedLicenses = _dartString(licensesText);

  dartOut.writeAsStringSync('''
// GENERATED by tool/generate_about_manifest.dart — do not edit by hand.

/// Application version (from [pubspec.yaml] before `+`).
const String kWaddleDisplayAppVersion = ${_dartString(appVersion)};

/// Build number (from [pubspec.yaml] after `+`).
const String kWaddleDisplayBuildNumber = ${_dartString(buildNumber)};

const String kDisplayProductLicenseId = 'ONC';

const String kDisplayProductLicenseName =
    'Open Non-Commercial License (ONC) v1.0';

const String kDisplayProductLicenseUrl = $escapedUrl;

const String kDisplayProductLicenseSummary = $escapedSummary;

/// Relative asset path for full `flutter pub licenses` output.
const String kDisplayThirdPartyLicensesAsset =
    'assets/generated/third_party_licenses.txt';

/// JSON array of `{name, version, license}` dependency rows.
const String kDisplayAboutDependenciesJson = ${_dartString(depsJson)};

/// Inline copy of third-party license text (mirrors bundled asset).
const String kDisplayThirdPartyLicensesText = $escapedLicenses;
''');

  stdout.writeln(
    'Wrote ${dartOut.path} ($appVersion+$buildNumber, ${deps.length} deps)',
  );
  stdout.writeln('Wrote $licensesPath (${licensesText.length} chars)');
}

String _dartString(String value) {
  return jsonEncode(value);
}

Map<String, String> _parseLockVersions(String lockText) {
  final versions = <String, String>{};
  String? current;
  for (final line in lockText.split('\n')) {
    final pkg = RegExp(r'^  ([a-zA-Z0-9_]+):$').firstMatch(line);
    if (pkg != null) {
      current = pkg.group(1);
      continue;
    }
    if (current != null) {
      final ver = RegExp(r'^    version: "(.+)"$').firstMatch(line);
      if (ver != null) {
        versions[current] = ver.group(1)!;
        current = null;
      }
    }
  }
  return versions;
}

class _DepEntry {
  _DepEntry({required this.name, this.path});
  final String name;
  final String? path;
}

List<_DepEntry> _parsePubspecDependencies(String yaml, String displayRoot) {
  final start = RegExp(r'^dependencies:\s*$', multiLine: true).firstMatch(yaml);
  if (start == null) return [];
  final lines = yaml.substring(start.end).split('\n');
  final out = <_DepEntry>[];
  String? currentName;
  String? currentPath;
  for (final rawLine in lines) {
    final raw = rawLine.trimRight();
    if (raw.trim().isEmpty) continue;
    if (RegExp(r'^[a-zA-Z]').hasMatch(raw)) break;
    final top = RegExp(r'^  ([a-zA-Z0-9_]+):\s*(.*)$').firstMatch(raw);
    if (top != null && !raw.startsWith('    ')) {
      if (currentName != null) {
        out.add(_DepEntry(name: currentName, path: currentPath));
      }
      currentName = top.group(1);
      currentPath = null;
      final inlinePath = RegExp(r'path:\s*(\S+)').firstMatch(top.group(2) ?? '');
      if (inlinePath != null) {
        currentPath = _resolvePackagePath(displayRoot, inlinePath.group(1)!);
      }
      continue;
    }
    final pathLine = RegExp(r'^    path:\s*(\S+)').firstMatch(raw);
    if (pathLine != null && currentName != null) {
      currentPath = _resolvePackagePath(displayRoot, pathLine.group(1)!);
    }
  }
  if (currentName != null) {
    out.add(_DepEntry(name: currentName, path: currentPath));
  }
  return out;
}

String _resolvePackagePath(String displayRoot, String rel) {
  return Directory('$displayRoot/$rel').absolute.path;
}
