import 'dart:io';
import 'dart:typed_data';

import 'package:sqlite3/sqlite3.dart';

/// Double-quote an SQLite identifier (table/column name).
String quoteSqliteIdent(String name) => '"${name.replaceAll('"', '""')}"';

/// Format a Dart value as an SQLite literal for INSERT scripts.
String formatSqliteSeedLiteral(Object? value) {
  if (value == null) {
    return 'NULL';
  }
  if (value is bool) {
    return value ? '1' : '0';
  }
  if (value is int) {
    return value.toString();
  }
  if (value is BigInt) {
    return value.toString();
  }
  if (value is double) {
    if (value.isNaN || value.isInfinite) {
      throw ArgumentError.value(
        value,
        'value',
        'Unsupported float in SQL export',
      );
    }
    return value.toString();
  }
  if (value is String) {
    return "'${value.replaceAll("'", "''")}'";
  }
  if (value is Uint8List) {
    return _hexBlobLiteral(value);
  }
  if (value is List<int>) {
    return _hexBlobLiteral(Uint8List.fromList(value));
  }
  throw ArgumentError.value(
    value,
    'value',
    'Unsupported column type for SQL export',
  );
}

String _hexBlobLiteral(Uint8List bytes) {
  final b = StringBuffer("X'");
  for (var i = 0; i < bytes.length; i++) {
    b.write(bytes[i].toRadixString(16).padLeft(2, '0'));
  }
  b.write("'");
  return b.toString();
}

String _utcTimestampZ() {
  final t = DateTime.now().toUtc();
  String two(int n) => n.toString().padLeft(2, '0');
  return '${t.year}-${two(t.month)}-${two(t.day)}T'
      '${two(t.hour)}:${two(t.minute)}:${two(t.second)}Z';
}

List<String> _listUserTables(Database db) {
  final rs = db.select("""
    SELECT name FROM sqlite_master
    WHERE type = 'table'
      AND name NOT LIKE 'sqlite_%'
    ORDER BY name
    """);
  return [for (final row in rs) row.columnAt(0) as String];
}

bool _hasSqliteSequenceTable(Database db) {
  final rs = db.select(
    "SELECT 1 FROM sqlite_master WHERE type='table' AND name='sqlite_sequence' LIMIT 1",
  );
  return rs.isNotEmpty;
}

List<String> _tableColumnNames(Database db, String table) {
  final quoted = quoteSqliteIdent(table);
  final rs = db.select('PRAGMA table_info($quoted)');
  final rows = <({int cid, String name})>[];
  for (final row in rs) {
    final cid = row.columnAt(0) as int;
    final name = row.columnAt(1) as String;
    rows.add((cid: cid, name: name));
  }
  rows.sort((a, b) => a.cid.compareTo(b.cid));
  return [for (final r in rows) r.name];
}

int _emitTableInserts(
  Database db,
  String table,
  List<String> colNames,
  List<String> outLines,
) {
  if (colNames.isEmpty) {
    return 0;
  }
  final qcols = colNames.map(quoteSqliteIdent).join(', ');
  final quotedTable = quoteSqliteIdent(table);
  final rs = db.select('SELECT $qcols FROM $quotedTable');
  var count = 0;
  for (final row in rs) {
    final valuesSql = List.generate(
      colNames.length,
      (i) => formatSqliteSeedLiteral(row.columnAt(i)),
    ).join(', ');
    outLines.add('INSERT INTO $quotedTable ($qcols) VALUES ($valuesSql);');
    count++;
  }
  return count;
}

/// Data-only SQL seed script: DELETE (FKs off), optional [sqlite_sequence] reset, INSERTs.
///
/// Apply only against a database that already matches the app schema version.
String exportSqliteSeedSql(
  File dbFile, {
  bool includeSqliteSequenceRows = false,
}) {
  final resolved = dbFile.absolute;
  final db = sqlite3.open(resolved.path, mode: OpenMode.readOnly);
  try {
    final tables = _listUserTables(db);
    final lines = <String>[];
    final utc = _utcTimestampZ();
    lines.add('-- Generated by waddlectl sqlite export-seed at $utc');
    lines.add('-- Source database: $resolved');
    lines.add(
      '-- Data-only seed: requires matching Drift schema on the target file.',
    );
    lines.add('PRAGMA foreign_keys=OFF;');
    lines.add('BEGIN IMMEDIATE;');

    if (_hasSqliteSequenceTable(db)) {
      lines.add('DELETE FROM sqlite_sequence;');
    }

    for (final t in tables.reversed) {
      lines.add('DELETE FROM ${quoteSqliteIdent(t)};');
    }

    var totalInserts = 0;
    for (final t in tables) {
      final colNames = _tableColumnNames(db, t);
      totalInserts += _emitTableInserts(db, t, colNames, lines);
    }

    if (includeSqliteSequenceRows && _hasSqliteSequenceTable(db)) {
      final seqNames = _tableColumnNames(db, 'sqlite_sequence');
      if (seqNames.isNotEmpty) {
        _emitTableInserts(db, 'sqlite_sequence', seqNames, lines);
      }
    }

    lines.add('COMMIT;');
    lines.add('PRAGMA foreign_keys=ON;');
    lines.add('-- Rows exported (INSERT statements): $totalInserts');

    return '${lines.join('\n')}\n';
  } finally {
    db.close();
  }
}
